### ISSUE TITLE
README mistake

### ISSUE THREAD

**Issue by hundun000** [raeleus/stripe#7]
https://github.com/raeleus/stripe/blob/187471f57aae3c0e0793077c88207bbdaabd97ee/README.md?plain=1#L28

Should be `com.github.raeleus:stripe:1.4.1`.  Likes [in viewports-sample-project](https://github.com/raeleus/viewports-sample-project/blob/306eceb6aa9e3cd83dc9a095a1d456ff763242d8/core/build.gradle#L6).

The same with other `com.github.raeleus.stripe` in README.

**Comment by raeleus** [comment]
The new format is correct. This is because there are subprojects for PopColorPicker and FreeTypeSkin. Viewports sample project uses an old version. Thanks for checking though!

**Comment by hundun000** [comment]
Oh I know why I can't use it before. I copy the README single quotation marks version and try to use version number variable, and gradle can't handle it, then I copy the old version double quotation marks so it works.
